### ISSUE TITLE
Provide the possibility to attach VLANs to VMs

### ISSUE THREAD

**Issue by martin-huber** [cloudsigma/terraform-provider-cloudsigma#5] opened 2020-11-26 08:29 UTC
It already is great, that we now can create and mostly manage our Cloudsigma VMs with terraform.

There are a few features missing for us at the moment, that still require us to do a couple of manual steps in the Web-UI after VM creation.

One of these is: 
remove the public IP that had been assigned to the VM and attach our VLAN with the private network interface to it.

There already is a data provider to find our VLAN instance - but we cannot yet attach its UUID to the VM.

It would be great, if this also could be done.

**Comment by pavel-github** [comment] 2020-11-26 10:36
Yes, we're working on it and I will update you when the new version is available.

**Comment by pavel-github** [comment] 2021-02-17 01:02
👋 @martin-huber, we added ability to configure network interfaces in our plugin. Do you wanna try a new version v1.2.0 and check whether the issue is solved?

[Here](https://registry.terraform.io/providers/cloudsigma/cloudsigma/latest/docs/resources/server#network) is the link to documentation snippet you'll need. I guess in your case a server configuration would look so:
```hcl
resource "cloudsigma_server" "main" {
  cpu          = 1000              # 1GHz CPU
  memory       = 512 * 1024 * 1024 # 512MB RAM
  name         = "main"
  vnc_password = "asdf1234"

  network {
    vlan_uuid = "<insert-vlan-uuid-here>"
  }
}
```

**Comment by martin-huber** [comment] 2021-02-17 13:05
Hi Pavel,
that's great to hear, thanks for the notification !

Unfortunately, after I `terraform init -upgrade` to the new provider version, I get another stacktrace during "refresh":

```
panic: interface conversion: cty.PathStep is cty.IndexStep, not cty.GetAttrStep
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: goroutine 115 [running]:
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation.ToDiagFunc.func1(0x118c780, 0xc00072ca60, 0xc000516500, 0x2, 0x2, 0x1222f60, 0x18, 0x1178960)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/validation/meta.go:69 +0x586
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Schema).validateFunc(0xc0000e8c80, 0x118c780, 0xc00072ca60, 0xc00074c190, 0xa, 0xc000516500, 0x2, 0x2, 0x11d1d80, 0x11c491b28f8, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:434 +0x5b6
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validatePrimitive(0xc000608a20, 0xc00074c190, 0xa, 0x118c780, 0xc00072c220, 0xc0000e8c80, 0xc0007306f0, 0xc000516500, 0x2, 0x2, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2083 +0x358
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0xc000608a20, 0xc00074c190, 0xa, 0x118c780, 0xc00072c220, 0xc0000e8c80, 0xc0007306f0, 0xc000516500, 0x2, 0x2, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2108 +0x40b
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateList(0xc000608a20, 0x134227b, 0x8, 0x1178960, 0xc0005163e0, 0xc0000e8dc0, 0xc0007306f0, 0xc00072c920, 0x1, 0x1, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1758 +0x77f
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0xc000608a20, 0x134227b, 0x8, 0x1178960, 0xc0005163e0, 0xc0000e8dc0, 0xc0007306f0, 0xc00072c920, 0x1, 0x1, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2100 +0xdd
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validate(0xc000608a20, 0x134227b, 0x8, 0xc0000e8dc0, 0xc0007306f0, 0xc00072c920, 0x1, 0x1, 0x0, 0x0, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1531 +0x8c9
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateObject(0xc000608a20, 0x0, 0x0, 0xc000608a20, 0xc0007306f0, 0x1ad9960, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1967 +0x2af
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Validate(...)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:646
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Validate(0xc00017d500, 0xc0007306f0, 0xc00073a000, 0x11, 0xc00045b908)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:471 +0x75
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ValidateResource(0xc00007e820, 0xc00073a000, 0x11, 0xc0007306f0, 0xc0007300c0, 0xc0007306f0, 0xc000744018)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/provider.go:251 +0x16c
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ValidateResourceTypeConfig(0xc00028e4a0, 0x14cb7c0, 0xc00072a180, 0xc000516120, 0xc00072a180, 0x12aa640, 0x12f3a80)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:230 +0x1e5
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ValidateResourceTypeConfig(0xc0005ae860, 0x14cb7c0, 0xc00072a180, 0xc00072a140, 0xc0005ae860, 0xc000730000, 0xc000577ba0)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:264 +0xd8
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ValidateResourceTypeConfig_Handler(0x12f3a80, 0xc0005ae860, 0x14cb880, 0xc000730000, 0xc0007280c0, 0x0, 0x14cb880, 0xc000730000, 0xc00072e000, 0xbd)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:272 +0x214
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000008380, 0x14d6800, 0xc000604900, 0xc00021a000, 0xc0005a4570, 0x1a97fd0, 0x0, 0x0, 0x0)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).handleStream(0xc000008380, 0x14d6800, 0xc000604900, 0xc00021a000, 0x0)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd25
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002d43a0, 0xc000008380, 0x14d6800, 0xc000604900, 0xc00021a000)
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa8
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-17T14:01:21.361+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```
Maybe you can recognize the problem with that ?
Else we will not be able to update to 1.2.0 .

Thanks !

**Comment by martin-huber** [comment] 2021-02-17 13:10
P.S. after I updated to the latest terraform version 0.14.6, the stacktrace is:
```
panic: interface conversion: cty.PathStep is cty.IndexStep, not cty.GetAttrStep
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: goroutine 210 [running]:
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation.ToDiagFunc.func1(0x118c780, 0xc00067a720, 0xc00030a400, 0x2, 0x2, 0x1222f60, 0x18, 0x1178960)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/validation/meta.go:69 +0x586
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Schema).validateFunc(0xc0007c6c80, 0x118c780, 0xc00067a720, 0xc0008241e0, 0xa, 0xc00030a400, 0x2, 0x2, 0x11d1d80, 0x22227bc1ba8, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:434 +0x5b6
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validatePrimitive(0xc000380930, 0xc0008241e0, 0xa, 0x118c780, 0xc00067a1b0, 0xc0007c6c80, 0xc00060ac00, 0xc00030a400, 0x2, 0x2, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2083 +0x358
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0xc000380930, 0xc0008241e0, 0xa, 0x118c780, 0xc00067a1b0, 0xc0007c6c80, 0xc00060ac00, 0xc00030a400, 0x2, 0x2, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2108 +0x40b
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateList(0xc000380930, 0x134227b, 0x8, 0x1178960, 0xc00030a2e0, 0xc0007c6dc0, 0xc00060ac00, 0xc00067a5e0, 0x1, 0x1, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1758 +0x77f
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateType(0xc000380930, 0x134227b, 0x8, 0x1178960, 0xc00030a2e0, 0xc0007c6dc0, 0xc00060ac00, 0xc00067a5e0, 0x1, 0x1, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:2100 +0xdd
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validate(0xc000380930, 0x134227b, 0x8, 0xc0007c6dc0, 0xc00060ac00, 0xc00067a5e0, 0x1, 0x1, 0x0, 0x0, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1531 +0x8c9
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.validateObject(0xc000380930, 0x0, 0x0, 0xc000380930, 0xc00060ac00, 0x1ad9960, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:1967 +0x2af
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Validate(...)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/schema.go:646
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Validate(0xc00011d500, 0xc00060ac00, 0xc00069a060, 0x11, 0xc0005c71b8)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:471 +0x75
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ValidateResource(0xc00007e190, 0xc00069a060, 0x11, 0xc00060ac00, 0xc00060a090, 0xc00060ac00, 0xc00081c040)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/provider.go:251 +0x16c
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ValidateResourceTypeConfig(0xc000004240, 0x14cb7c0, 0xc0005fe040, 0xc00030a020, 0xc0005fe040, 0x12aa640, 0x12f3a80)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:230 +0x1e5
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ValidateResourceTypeConfig(0xc000525940, 0x14cb7c0, 0xc0005fe040, 0xc0005fe000, 0xc000525940, 0xc00060a000, 0xc000a03ba0)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:264 +0xd8
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ValidateResourceTypeConfig_Handler(0x12f3a80, 0xc000525940, 0x14cb880, 0xc00060a000, 0xc0006f4120, 0x0, 0x14cb880, 0xc00060a000, 0xc00051a000, 0xbd)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:272 +0x214
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005b2700, 0x14d6800, 0xc000582c00, 0xc0006a0000, 0xc0005c4660, 0x1a97fd0, 0x0, 0x0, 0x0)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).handleStream(0xc0005b2700, 0x14d6800, 0xc000582c00, 0xc0006a0000, 0x0)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd25
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002fa420, 0xc0005b2700, 0x14d6800, 0xc000582c00, 0xc0006a0000)
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa8
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-17T14:09:04.058+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.2.0.exe: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by martin-huber** [comment] 2021-02-17 13:11
P.P.S.
The above errors were during just the refresh of our existing code base w/o any change, so I even did not test the new VLAN feature

**Comment by pavel-github** [comment] 2021-02-17 22:45
🤔, would you mind to share your terraform configuration file (excluding sensitive info) with us and terraform version.
P.S.: I see only Terraform SDK code in stacktrace, but I have an idea what might be here. At the moment Terraform SDK replace error handling with diagnostic structure and it looks to me there is bug somewhere in SDK.

**Comment by martin-huber** [comment] 2021-02-18 13:09
I was using the latest terraform version - 0.14.6 .
But before I tried with 0.14.2 and there there was the same problem (see 1st and 2nd stacktrace).
And the crash only occured after updating to terraform-provider-cloudsigma_v1.2.0 , with terraform-provider-cloudsigma_v1.0.1 there was no problem.

I try to send you our terraform configuration by email, if possible, or a share link to it.
Do you also need the terraform.tfstate ? I think this is primarily used for a "refresh" ?

**Comment by martin-huber** [comment] 2021-02-18 13:55
ok, here we go - I replaced all the VNC passwords and SSH key ids ...
The .zip also included the crash.log, it doesn't seem to contain sensitive info.

[terraform-config.zip](https://github.com/cloudsigma/terraform-provider-cloudsigma/files/6003244/terraform-config.zip)

Cheers,
Martin

**Comment by pavel-github** [comment] 2021-02-18 13:56
Thanks, Martin. I'm going to take a look on it and will ping you back.

**Comment by pavel-github** [comment] 2021-02-18 17:58
@martin-huber, I found the issue: there are some changes internally in Terraform SDK how differnt value types are handled.
It should be fixed with `1.2.1` version 🤞.

**Comment by pavel-github** [comment] 2021-02-18 18:00
We'll add an acceptance tests for this behavior to catch such kind of issues in the future.

**Comment by martin-huber** [comment] 2021-02-19 10:52
> @martin-huber, I found the issue: there are some changes internally in Terraform SDK how different value types are handled.
> It should be fixed with `1.2.1` version 🤞.

Hi pavel, I updated to 1.2.1 and the refresh/plan with our existing config worked again ! 👍 

Addtionally I introduced the vlan network in all our host definitions and als tested it with a new VM and it is working like a charm.

There only are 2 possible improvements:

1. I don't want to specify the uuid of our VLAN in the VM config itself, but I want to have a module with an output that found our VLAN by a resource/data search. I designed it that way, and it is working great, as long as I use a search filter for the uuid in the resource search: 
```
data "cloudsigma_vlan" "vlan_lan" {
  filter {
    name   = "uuid"
    values = ["28c024fa-6a91-4b8e-80f5-4e9b7ea3b13d"]
  }
}
```
But in fact I don't want to search for the uuid, but for the name of the VLAN. 
Unfortunately `name = "name"` does not work, and if I look into the JSON response of the vlans API output:
```
  "meta": {
    "description": "",
    "name": "LAN"
  },
```
I see that the `name` is in a `meta ` child object. I tried to filter for `name = "meta.name"` but this also did not find the VLAN.
Do you have any idea for that ?

2. If I add a new VM and do `terraform apply`  after the `plan`, I  often get timeout errors while terraform is waiting for the VM creation. Usually it waits long enough to see the drive being created, but afterwards, the creation of the VM then all-in-all takes too long ...
Can there something be done on your side, to configure longer timeouts, provide better feedback towards terraform ? 
I tried to search, if there are timeouts in terraform , but I think, I have read somewhere, that such configuration parameters and behavior is provider-specific ... 
Would be great, if this also could be "smoothed"

**Comment by martin-huber** [comment] 2021-02-19 10:52
> We'll add an acceptance tests for this behavior to catch such kind of issues in the future.

Great, highly appreciate that ! 👍

**Comment by pavel-github** [comment] 2021-02-19 14:50
Thanks for feedback, glad to hear that it works.
Good points about filtering for VLANs and timeouts. How about tracking this in a separate issue, so I would like to keep the scope and focus of issues small?

**Comment by pavel-github** [comment] 2021-02-19 14:57
Request for filtering #14.

**Comment by pavel-github** [comment] 2021-02-19 15:01
Issue for timeouts #15

**Comment by martin-huber** [comment] 2021-02-19 16:26
> Thanks for feedback, glad to hear that it works.
> Good points about filtering for VLANs and timeouts. How about tracking this in a separate issue, so I would like to keep the scope and focus of issues small?

You're right, of course. Thanks for creating the related issues !

**Closed** 2021-02-19 17:12 UTC
Labels: enhancement
