### ISSUE TITLE
'terraform refresh' crashes if a VM is not running

### ISSUE THREAD

**Issue by martin-huber** [cloudsigma/terraform-provider-cloudsigma#3] opened 2020-11-25 12:56 UTC
`
panic: runtime error: invalid memory address or nil pointer dereference
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0xf01935]
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe:
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe: goroutine 68 [running]:
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe: github.com/cloudsigma/terraform-provider-cloudsigma/cloudsigma.findIPv4Address(0xc000014b40, 0x11b5e00, 0x6, 0xfba940, 0xc00080fb58)
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe:   github.com/cloudsigma/terraform-provider-cloudsigma/cloudsigma/resource_cloudsigma_server.go:275 +0x45
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe: github.com/cloudsigma/terraform-provider-cloudsigma/cloudsigma.resourceCloudSigmaServerRead(0x14388e0, 0xc0006448a0, 0xc0005ad100, 0x10871a0, 0xc0005c0a80, 0xc0002ba340, 0xc0005458f0, 0x40d3df)
2020-11-25T13:47:53.274+0100 [DEBUG] plugin.terraform-provider-cloudsigma_v1.0.0.exe:   github.com/cloudsigma/terraform-provider-cloudsigma/cloudsigma/resource_cloudsigma_server.go:174 +0x220
`

The reason is, that the REST response does have a 
`  "runtime": null,
`
for VMs that are not running !

But you are trying to retrieve an IPv4 address info from there:
`
func findIPv4Address(server *cloudsigma.Server, addrType string) string {
	for _, nic := range server.Runtime.RuntimeNICs {
		if nic.InterfaceType == addrType {
			return nic.IPv4.UUID
		}
	}
	return ""
}
`

**Comment by pavel-github** [comment] 2020-11-25 15:12
Hi @martin-huber,

I can reproduce the issue and have all needed infomration in the stacktrace. We'll fix it with `v1.0.1` version. I'll ping you back when a new version is released.

Thanks, Pavel.

**Comment by pavel-github** [comment] 2020-11-25 21:38
👋 @martin-huber,
we released a new version `v1.0.1` and it's available on Terraform Registry: https://registry.terraform.io/providers/cloudsigma/cloudsigma/1.0.1.
Could you confirm that the issue is fixed? If yes, I can close the issue.

**Comment by martin-huber** [comment] 2020-11-26 08:15
@pavel-github - I tried it and can confirm, that it is now working like a charm 👍 
Thanks for the quick fix !

**Closed** 2020-11-26 10:34 UTC
Labels: bug
